kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: f1-telemetry
nodes:
- role: control-plane
  extraPortMappings:
  # Ingestion Service
  - containerPort: 30080
    hostPort: 30080
    protocol: TCP
  # Prometheus
  - containerPort: 30090
    hostPort: 30090
    protocol: TCP
  # Grafana
  - containerPort: 30030
    hostPort: 30030
    protocol: TCP
- role: worker
- role: worker
